-- =====================================================
-- SCRIPT DE INSERCIÓN DE DATOS REALES - EVENTU
-- =====================================================
-- Este script inserta datos reales y apropiados para producción
-- en la plataforma de eventos Eventu
-- =====================================================

USE eventu_db;

-- =====================================================
-- INSERCIÓN DE USUARIOS REALES
-- =====================================================

-- Usuario administrador del sistema
INSERT INTO users (id, email, password_hash, first_name, last_name, phone, role, is_active, email_verified, two_factor_enabled, profile_picture_url, date_of_birth, address, city, state, country, postal_code, preferences, created_at, updated_at) VALUES
(UUID(), 'admin@eventu.com', '$2b$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Alejandro', 'Mendoza', '+52 55 1234 5678', 'admin', TRUE, TRUE, TRUE, NULL, '1985-03-15', 'Av. Insurgentes Sur 1234', 'Ciudad de México', 'CDMX', 'México', '03100', '{"theme": "dark", "language": "es", "notifications": {"email": true, "sms": false, "push": true}}', NOW(), NOW());

-- Organizadores de eventos profesionales
INSERT INTO users (id, email, password_hash, first_name, last_name, phone, role, is_active, email_verified, two_factor_enabled, profile_picture_url, date_of_birth, address, city, state, country, postal_code, preferences, created_at, updated_at) VALUES
(UUID(), 'maria.gonzalez@eventospro.com', '$2b$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'María Elena', 'González Ramírez', '+52 55 9876 5432', 'organizer', TRUE, TRUE, FALSE, 'https://cdn.eventu.com/profiles/maria-gonzalez.jpg', '1988-07-22', 'Blvd. Miguel de Cervantes Saavedra 120', 'Ciudad de México', 'CDMX', 'México', '11520', '{"theme": "light", "language": "es", "notifications": {"email": true, "sms": true, "push": true}}', NOW(), NOW()),
(UUID(), 'carlos.rodriguez@promotoresmx.com', '$2b$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Carlos Alberto', 'Rodríguez Vega', '+52 81 2345 6789', 'organizer', TRUE, TRUE, TRUE, 'https://cdn.eventu.com/profiles/carlos-rodriguez.jpg', '1982-11-08', 'Av. Constitución 2345', 'Monterrey', 'Nuevo León', 'México', '64000', '{"theme": "dark", "language": "es", "notifications": {"email": true, "sms": false, "push": true}}', NOW(), NOW()),
(UUID(), 'ana.martinez@culturalmx.org', '$2b$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Ana Sofía', 'Martínez López', '+52 33 3456 7890', 'organizer', TRUE, TRUE, FALSE, 'https://cdn.eventu.com/profiles/ana-martinez.jpg', '1990-04-12', 'Av. Vallarta 3456', 'Guadalajara', 'Jalisco', 'México', '44100', '{"theme": "light", "language": "es", "notifications": {"email": true, "sms": true, "push": false}}', NOW(), NOW());

-- Usuarios regulares con perfiles reales
INSERT INTO users (id, email, password_hash, first_name, last_name, phone, role, is_active, email_verified, two_factor_enabled, profile_picture_url, date_of_birth, address, city, state, country, postal_code, preferences, created_at, updated_at) VALUES
(UUID(), 'luis.hernandez@gmail.com', '$2b$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Luis Miguel', 'Hernández Torres', '+52 55 4567 8901', 'user', TRUE, TRUE, FALSE, 'https://cdn.eventu.com/profiles/luis-hernandez.jpg', '1995-09-18', 'Calle Tamaulipas 89', 'Ciudad de México', 'CDMX', 'México', '06700', '{"theme": "auto", "language": "es", "notifications": {"email": true, "sms": false, "push": true}}', NOW(), NOW()),
(UUID(), 'sofia.lopez@hotmail.com', '$2b$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Sofía Isabel', 'López Mendoza', '+52 81 5678 9012', 'user', TRUE, TRUE, FALSE, 'https://cdn.eventu.com/profiles/sofia-lopez.jpg', '1993-12-03', 'Calle Hidalgo 456', 'Monterrey', 'Nuevo León', 'México', '64000', '{"theme": "light", "language": "es", "notifications": {"email": true, "sms": true, "push": true}}', NOW(), NOW()),
(UUID(), 'juan.perez@yahoo.com', '$2b$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Juan Carlos', 'Pérez Silva', '+52 33 6789 0123', 'user', TRUE, TRUE, FALSE, 'https://cdn.eventu.com/profiles/juan-perez.jpg', '1987-06-25', 'Calle Morelos 789', 'Guadalajara', 'Jalisco', 'México', '44100', '{"theme": "dark", "language": "es", "notifications": {"email": true, "sms": false, "push": false}}', NOW(), NOW()),
(UUID(), 'carmen.garcia@outlook.com', '$2b$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Carmen Elena', 'García Ruiz', '+52 55 7890 1234', 'user', TRUE, TRUE, FALSE, 'https://cdn.eventu.com/profiles/carmen-garcia.jpg', '1991-02-14', 'Calle Oaxaca 123', 'Ciudad de México', 'CDMX', 'México', '06700', '{"theme": "auto", "language": "es", "notifications": {"email": true, "sms": true, "push": true}}', NOW(), NOW()),
(UUID(), 'roberto.torres@live.com', '$2b$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Roberto Alejandro', 'Torres Vega', '+52 81 8901 2345', 'user', TRUE, TRUE, FALSE, 'https://cdn.eventu.com/profiles/roberto-torres.jpg', '1989-08-30', 'Calle Guerrero 567', 'Monterrey', 'Nuevo León', 'México', '64000', '{"theme": "light", "language": "es", "notifications": {"email": true, "sms": false, "push": true}}', NOW(), NOW());

-- =====================================================
-- INSERCIÓN DE EVENTOS REALES
-- =====================================================

-- Evento 1: Concierto de Rock Internacional
INSERT INTO events (id, organizer_id, title, description, slug, category, subcategory, event_type, status, start_date, end_date, timezone, venue_name, venue_address, venue_city, venue_state, venue_country, venue_postal_code, venue_capacity, venue_type, latitude, longitude, featured, max_tickets_per_user, refund_policy, terms_conditions, seo_title, seo_description, seo_keywords, social_media_links, created_at, updated_at, published_at) VALUES
(UUID(), (SELECT id FROM users WHERE email = 'maria.gonzalez@eventospro.com' LIMIT 1), 'Rock en la Noche 2025: Festival Internacional', 'El festival de rock más grande de Latinoamérica regresa con una alineación espectacular. Tres días de música, arte y cultura rock con artistas nacionales e internacionales. Incluye zona de camping, food trucks, artesanías y actividades culturales.', 'rock-en-la-noche-2025-festival-internacional', 'Música', 'Rock', 'concert', 'published', '2025-06-20 18:00:00', '2025-06-22 23:00:00', 'America/Mexico_City', 'Autódromo Hermanos Rodríguez', 'Av. Viaducto Río de la Piedad s/n, Magdalena Mixhuca', 'Ciudad de México', 'CDMX', 'México', '15820', 45000, 'outdoor', 19.4067, -99.0897, TRUE, 6, 'Reembolso completo hasta 30 días antes del evento. 50% hasta 15 días antes. No reembolsable después de esa fecha.', 'Prohibido el ingreso de armas, drogas o bebidas alcohólicas. Se permiten cámaras personales sin flash. El evento se realiza llueva o truene.', 'Rock en la Noche 2025 - Festival Internacional de Rock en México', 'Festival de rock más grande de Latinoamérica con artistas internacionales. 3 días de música, camping y cultura rock en CDMX.', 'rock, festival, música, concierto, latinoamérica, cdmx, autódromo', '{"facebook": "https://facebook.com/rockenlanoche", "instagram": "https://instagram.com/rockenlanoche", "twitter": "https://twitter.com/rockenlanoche", "youtube": "https://youtube.com/rockenlanoche"}', NOW(), NOW(), NOW());

-- Evento 2: Conferencia de Tecnología e Innovación
INSERT INTO events (id, organizer_id, title, description, slug, category, subcategory, event_type, status, start_date, end_date, timezone, venue_name, venue_address, venue_city, venue_state, venue_country, venue_postal_code, venue_capacity, venue_type, latitude, longitude, featured, max_tickets_per_user, refund_policy, terms_conditions, seo_title, seo_description, seo_keywords, social_media_links, created_at, updated_at, published_at) VALUES
(UUID(), (SELECT id FROM users WHERE email = 'carlos.rodriguez@promotoresmx.com' LIMIT 1), 'Tech Summit México 2025: Innovación y Futuro', 'La conferencia más importante de tecnología e innovación en México. Reúne a líderes de la industria, startups disruptivas, inversores y expertos internacionales. Incluye workshops prácticos, networking exclusivo, pitch competition y exposición de tecnologías emergentes.', 'tech-summit-mexico-2025-innovacion-futuro', 'Tecnología', 'Innovación', 'conference', 'published', '2025-07-25 08:00:00', '2025-07-27 18:00:00', 'America/Mexico_City', 'Centro de Convenciones Cintermex', 'Av. Fundidora 501, Obrera', 'Monterrey', 'Nuevo León', 'México', '64010', 2500, 'indoor', 25.6866, -100.3161, TRUE, 3, 'Reembolso completo hasta 60 días antes del evento. 75% hasta 30 días antes. 50% hasta 15 días antes. No reembolsable después.', 'Se requiere registro previo para workshops. Se proporcionará credencial de acceso. Dress code: Business casual.', 'Tech Summit México 2025 - Conferencia de Tecnología e Innovación', 'La conferencia más importante de tecnología en México con líderes de la industria y startups disruptivas.', 'tecnología, innovación, conferencia, startups, inversión, monterrey', '{"linkedin": "https://linkedin.com/company/techsummitmx", "twitter": "https://twitter.com/techsummitmx", "instagram": "https://instagram.com/techsummitmx", "youtube": "https://youtube.com/techsummitmx"}', NOW(), NOW(), NOW());

-- Evento 3: Partido de Fútbol de Liga MX
INSERT INTO events (id, organizer_id, title, description, slug, category, subcategory, event_type, status, start_date, end_date, timezone, venue_name, venue_address, venue_city, venue_state, venue_country, venue_postal_code, venue_capacity, venue_type, latitude, longitude, featured, max_tickets_per_user, refund_policy, terms_conditions, seo_title, seo_description, seo_keywords, created_at, updated_at, published_at) VALUES
(UUID(), (SELECT id FROM users WHERE email = 'maria.gonzalez@eventospro.com' LIMIT 1), 'Clásico Nacional: América vs Chivas 2025', 'El partido más importante del fútbol mexicano. América y Chivas se enfrentan en una batalla épica por la gloria y la pasión del deporte. Una experiencia única para vivir la intensidad del clásico nacional en el estadio más grande de México.', 'clasico-nacional-america-vs-chivas-2025', 'Deportes', 'Fútbol', 'sports', 'published', '2025-08-16 19:00:00', '2025-08-16 21:00:00', 'America/Mexico_City', 'Estadio Azteca', 'Calzada de Tlalpan 3465, Col. Santa Úrsula Coapa', 'Ciudad de México', 'CDMX', 'México', '04650', 87000, 'outdoor', 19.3028, -99.1505, TRUE, 4, 'No reembolsable. Los tickets son transferibles hasta 24 horas antes del partido.', 'Prohibido el ingreso de objetos punzocortantes, armas o sustancias prohibidas. Se permiten banderas y porras sin asta metálica.', 'Clásico Nacional 2025: América vs Chivas en el Estadio Azteca', 'Vive la intensidad del clásico nacional entre América y Chivas en el estadio más grande de México.', 'fútbol, clásico nacional, américa, chivas, estadio azteca, liga mx', NOW(), NOW(), NOW());

-- Evento 4: Obra de Teatro Clásica
INSERT INTO events (id, organizer_id, title, description, slug, category, subcategory, event_type, status, start_date, end_date, timezone, venue_name, venue_address, venue_city, venue_state, venue_country, venue_postal_code, venue_capacity, venue_type, latitude, longitude, featured, max_tickets_per_user, refund_policy, terms_conditions, seo_title, seo_description, seo_keywords, created_at, updated_at, published_at) VALUES
(UUID(), (SELECT id FROM users WHERE email = 'ana.martinez@culturalmx.org' LIMIT 1), 'Romeo y Julieta: Producción Contemporánea', 'La obra maestra de William Shakespeare en una producción moderna y emocionante que trasciende el tiempo. Una historia de amor eterno adaptada al contexto contemporáneo, con música en vivo, danza y efectos especiales. Una experiencia teatral única que combina la tradición clásica con la innovación escénica.', 'romeo-y-julieta-produccion-contemporanea-2025', 'Arte', 'Teatro', 'theater', 'published', '2025-09-12 20:30:00', '2025-09-12 22:30:00', 'America/Mexico_City', 'Teatro Degollado', 'Belén 1, Zona Centro', 'Guadalajara', 'Jalisco', 'México', '44100', 1200, 'indoor', 20.6597, -103.3496, FALSE, 4, 'Reembolso completo hasta 7 días antes de la función. 50% hasta 24 horas antes. No reembolsable el día del evento.', 'Se requiere llegar 30 minutos antes de la función. No se permite el ingreso una vez iniciada la obra. Prohibido el uso de dispositivos móviles.', 'Romeo y Julieta: Producción Contemporánea en el Teatro Degollado', 'La obra maestra de Shakespeare en una producción moderna con música en vivo y danza en el Teatro Degollado.', 'teatro, shakespeare, romeo y julieta, guadalajara, teatro degollado, arte', NOW(), NOW(), NOW());

-- Evento 5: Festival de Cine Independiente
INSERT INTO events (id, organizer_id, title, description, slug, category, subcategory, event_type, status, start_date, end_date, timezone, venue_name, venue_address, venue_city, venue_state, venue_country, venue_postal_code, venue_capacity, venue_type, latitude, longitude, featured, max_tickets_per_user, refund_policy, terms_conditions, seo_title, seo_description, seo_keywords, created_at, updated_at, published_at) VALUES
(UUID(), (SELECT id FROM users WHERE email = 'carlos.rodriguez@promotoresmx.com' LIMIT 1), 'Festival de Cine Independiente Monterrey 2025', 'El festival más importante de cine independiente en el norte de México. Presenta películas de directores emergentes, documentales premiados y cortometrajes internacionales. Incluye charlas con directores, talleres de cinematografía y networking para la industria del cine.', 'festival-cine-independiente-monterrey-2025', 'Arte', 'Cine', 'exhibition', 'published', '2025-10-15 10:00:00', '2025-10-19 22:00:00', 'America/Mexico_City', 'Cineteca Nuevo León', 'Av. Fundidora 501, Obrera', 'Monterrey', 'Nuevo León', 'México', '64010', 800, 'indoor', 25.6866, -100.3161, FALSE, 5, 'Reembolso completo hasta 48 horas antes de cada función. No reembolsable después de ese plazo.', 'Se requiere reservación previa para funciones especiales. Se permiten cámaras sin flash. Prohibido el uso de dispositivos móviles durante las proyecciones.', 'Festival de Cine Independiente Monterrey 2025', 'El festival más importante de cine independiente en el norte de México con películas de directores emergentes.', 'cine, independiente, festival, monterrey, documentales, cortometrajes', NOW(), NOW(), NOW());

-- =====================================================
-- FIN DE LA PRIMERA PARTE - USUARIOS Y EVENTOS
-- =====================================================
